### ISSUE TITLE
Try OpenFrameworks

### ISSUE THREAD

**Issue by ybakos** [osu-cascades/exhibit-x#10]
I just realized that there's a version of OpenFrameworks that runs on the Pi. I think we might get better performance. Let's try it!
http://openframeworks.cc/setup/raspberrypi/raspberry-pi-getting-started/

**Comment by ybakos** [comment]
Try a fresh image, follow the install instructions, and communicate errors here.

**Comment by NytroC** [comment]
ok installed a fresh image
followed how-to setup, got it installed and compiled
ran an example, interesting side-note, it doesn't show on the remote desktop when running but you can execute it from the remote desktop
