### ISSUE TITLE
Test out the usb microphone

### ISSUE THREAD

**Issue by ybakos** [osu-cascades/exhibit-x#3]

**Comment by NytroC** [comment]
like the kinect the example compiles but when I run it I get this error
[notice ] ofAppEGLWindow: setupPeripherals(): native event setup complete
connect(2) call to /tmp/jack-1000/default/jack_0 failed (err=No such file or directory)
attempt to connect to server failed

RtApiAlsa::getDeviceInfo: snd_pcm_open error for device (default), No such file or directory.

[notice ] ofBaseSoundStream::printDeviceList: 
[0] hw:bcm2835 ALSA,0 [in:0 out:2]
[1] hw:bcm2835 ALSA,1 [in:0 out:2]
[2] hw:USB PnP Sound Device,0 [in:1 out:0]
[3] default [in:0 out:2]

connect(2) call to /tmp/jack-1000/default/jack_0 failed (err=No such file or directory)
attempt to connect to server failed

RtApiAlsa::getDeviceInfo: snd_pcm_open error for device (default), No such file or directory.

**Comment by NytroC** [comment]
This might be a solution:
sudo modprobe snd_bcm2835
sudo amixer cset numid=3 1

**Comment by NytroC** [comment]
need to try ofxAudioAnalyzer

**Comment by NytroC** [comment]
unfortunately ofxAudioAnalyzer,  modprobe snd_bcm2835,  amixer cset numid=3 1 was not a solution. These did not get the microphone working.
