### ISSUE TITLE
Test the video camera

### ISSUE THREAD

**Issue by ybakos** [osu-cascades/exhibit-x#5]

**Comment by NytroC** [comment]
well, I got the camera to work but again, it doesn't seem to want to work with openFrameworks...

**Comment by NytroC** [comment]
I found a library ofxRPiCameraVideoGrabber and I got a simple example to work!

**Comment by ybakos** [comment]
Sweeeet.

**Comment by ybakos** [comment]
Please document

**Comment by NytroC** [comment]
added adding the ofxRPiCameraVideoGrabber library to the build instructions.
