### ISSUE TITLE
Get Remote Desktop working

### ISSUE THREAD

**Issue by ybakos** [osu-cascades/exhibit-x#6]

**Comment by NytroC** [comment]
Check

**Comment by ybakos** [comment]
Figure out how to connect as the existing user. (Should see same thing on the monitor as the remote window.)

**Comment by ybakos** [comment]
From the vnc session, open a terminal and `whoami` to check who you are logged in as.

**Comment by NytroC** [comment]
It looks like the default is to give each remote user its own session. There might be a way around this with x11vnc

**Comment by NytroC** [comment]
Ok with VNCviewer it mirrors the desktop!

**Comment by ybakos** [comment]
Niiiiiice.
