### ISSUE TITLE
Test Kinect

### ISSUE THREAD

**Issue by ybakos** [osu-cascades/exhibit-x#7]

**Comment by NytroC** [comment]
Tested the Kinect. It worked on my Mac with no issues. It says the Kinect library works with linux and there is a youtube video of it running the Kinect on a Pi. Will test when I get home.

**Comment by NytroC** [comment]
well unfortunately the kinect is not working on the pi.  The example compiles but throws this error when ran. 
Failed to open camera subdevice or it is not disabled.Failed to open motor subddevice or it is not disabled.Failed to open audio subdevice or it is not disabled.[ error ] ofxKinect: could not open device -1
[warning] ofxKinect: update(): device -1 isn't delivering data, reconnecting tries: 3

**Comment by NytroC** [comment]
looking into this 
https://github.com/OpenKinect/libfreenect/issues/439

**Comment by ybakos** [comment]
Please update the status in this ticket.

**Comment by NytroC** [comment]
OpenKinect/libfreenect#439 does work on Linux but not on the ARM architecture.
